language: rust
cache: cargo
before_cache:
    - rm -rf /home/travis/.cargo/registry/src/

addons:
    apt:
        packages:
            - libasound2-dev
matrix:
    include:
        - name: "Test nightly"
          rust: nightly

        - name: "Test beta"
          rust: beta

        - name: "Test stable"
          rust: stable

        - name: "Validate doc"
          rust: stable
          cache: 
            cargo: false
          script:
              - cargo doc --no-deps -v

before_script:
    - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        rustup component add rustfmt
      fi

script:
    - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        cargo fmt --all -- --check
      fi
    - cargo build -v
    - cargo test -v

